# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1459644be4b7e3c4b4ef2331b82bf67568903465c031d11c647f79eb068892b02dcbf01c35fc429bdbf9725e37f743b13dc525fc3e9b0fbecdab20cb89053d9b

test:
  secret_key_base: 82960d5b43c8f3a33b15b9b3ee2b6cda78d616cfec397a53fdfcd55bed59209849336af27bd1ef474b6427cdf9ecf7f0be50a9b9e0e005d249ec31bbd3c9e4b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
